# Generated by Django 3.2.8 on 2021-10-06 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custumer',
            fields=[
                ('id_custumer', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('telephone', models.IntegerField(max_length=11)),
                ('checkin', models.TimeField(default=django.utils.timezone.now)),
                ('checkout', models.TimeField(blank=True)),
            ],
        ),
    ]
