# Generated by Django 3.2.8 on 2021-10-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211006_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
