# Generated by Django 3.2.8 on 2021-10-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_custumer_checkout'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custumer',
            table='custumer',
        ),
    ]
